# This workflows will publish a Python Package to pypi using Poetry.
# It uses a github action developed by JRubics: https://github.com/marketplace/actions/publish-python-poetry-package

name: Upload Python Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
